# Branch Protection Configuration
# Configuración de protección de ramas para AuditMesh

branches:
  main:
    protection_rules:
      required_status_checks:
        strict: true
        contexts:
          - "code-quality"
          - "test"
          - "docker-build"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true

  develop:
    protection_rules:
      required_status_checks:
        strict: true
        contexts:
          - "code-quality"
          - "test"
          - "docker-build"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true

# Code Owners Configuration
codeowners:
  - "Neiland85"
