# Environments Configuration for AuditMesh
# Configuración de entornos para AuditMesh

environments:
  staging:
    name: Staging Environment
    url: https://staging.auditmesh.com
    protection_rules:
      required_reviewers:
        - "Neiland85"
      wait_timer: 0
      deployment_branch_policy:
        protected_branches: true
        custom_branch_policies: false
    variables:
      NODE_ENV: staging
      LOG_LEVEL: debug
      DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
    secrets:
      - name: STAGING_DATABASE_URL
        value: ${{ secrets.STAGING_DATABASE_URL }}
      - name: STAGING_API_KEY
        value: ${{ secrets.STAGING_API_KEY }}

  production:
    name: Production Environment
    url: https://auditmesh.com
    protection_rules:
      required_reviewers:
        - "Neiland85"
      wait_timer: 5
      deployment_branch_policy:
        protected_branches: true
        custom_branch_policies: false
    variables:
      NODE_ENV: production
      LOG_LEVEL: info
      DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
    secrets:
      - name: PRODUCTION_DATABASE_URL
        value: ${{ secrets.PRODUCTION_DATABASE_URL }}
      - name: PRODUCTION_API_KEY
        value: ${{ secrets.PRODUCTION_API_KEY }}
