# Security Configuration for AuditMesh
# Configuración de seguridad para AuditMesh

# Security Policy
security_policy:
  enabled: true
  contact_email: security@auditmesh.com
  responsible_disclosure: true
  bounty_program: false

# Code Scanning
code_scanning:
  enabled: true
  tools:
    - codeql
    - bandit
    - safety
    - semgrep
  schedule: weekly
  severity_threshold: MEDIUM

# Dependency Scanning
dependency_scanning:
  enabled: true
  tools:
    - dependabot
    - npm audit
    - pip-audit
  auto_fix: true
  schedule: daily

# Secret Scanning
secret_scanning:
  enabled: true
  push_protection: true
  custom_patterns:
    - name: "Custom API Key Pattern"
      pattern: "api_key.*=.*['\"][a-zA-Z0-9]{32,}['\"]"
      is_regex: true

# Branch Protection
branch_protection:
  main:
    require_status_checks: true
    require_pull_request_reviews: true
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    enforce_admins: true
  develop:
    require_status_checks: true
    require_pull_request_reviews: true
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    enforce_admins: false

# Vulnerability Alerts
vulnerability_alerts:
  enabled: true
  auto_dismiss: false
  notification_channels:
    - email
    - github
