version: '3.8'

services:
  auditmesh-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18-alpine
    image: auditmesh-frontend:latest
    container_name: auditmesh-frontend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3000
      - VITE_GATEWAY_URL=http://localhost:3000
      - VITE_DETECTOR_URL=http://localhost:3001
      - VITE_AUDITOR_URL=http://localhost:3002
    networks:
      - frontend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  frontend-network:
    driver: bridge
    name: frontend-network
