services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=auditmesh
      - POSTGRES_USER=auditmesh
      - POSTGRES_PASSWORD=auditmesh123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auditmesh-network

  ms-gateway:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: ./services/ms-gateway
      dockerfile: Dockerfile
    image: ${REGISTRY:-ghcr.io/neiland85-org}/ms-gateway:${GIT_SHA:-dev}
    container_name: ms-gateway
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${GATEWAY_PORT:-3000}
    ports:
      - "${GATEWAY_PORT:-3000}:3000"
    depends_on:
      - postgres
      - ms-lie-detector
      - ms-auditor
    networks:
      - auditmesh-network

  ms-lie-detector:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: ./services/ms-lie-detector
      dockerfile: Dockerfile
    image: ${REGISTRY:-ghcr.io/neiland85-org}/ms-lie-detector:${GIT_SHA:-dev}
    container_name: ms-lie-detector
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${LIE_DETECTOR_PORT:-3001}
    ports:
      - "${LIE_DETECTOR_PORT:-3001}:3001"
    depends_on:
      - postgres
    networks:
      - auditmesh-network

  ms-auditor:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: ./services/ms-auditor
      dockerfile: Dockerfile
    image: ${REGISTRY:-ghcr.io/neiland85-org}/ms-auditor:${GIT_SHA:-dev}
    container_name: ms-auditor
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${AUDITOR_PORT:-3002}
      - DATABASE_URL=postgresql://auditmesh:auditmesh123@postgres:5432/auditmesh
    ports:
      - "${AUDITOR_PORT:-3002}:3002"
    depends_on:
      - postgres
    networks:
      - auditmesh-network

  auditmesh-frontend:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18-alpine
    image: ${REGISTRY:-ghcr.io/neiland85-org}/auditmesh-frontend:${GIT_SHA:-dev}
    container_name: auditmesh-frontend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE_URL=http://ms-gateway:3000
      - VITE_GATEWAY_URL=http://ms-gateway:3000
      - VITE_DETECTOR_URL=http://ms-lie-detector:3001
      - VITE_AUDITOR_URL=http://ms-auditor:3002
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    depends_on:
      - ms-gateway
      - ms-lie-detector
      - ms-auditor
    networks:
      - auditmesh-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  auditmesh-network:
    driver: bridge
    name: auditmesh-network

volumes:
  postgres_data:
