version: '3.8'

# Development override for docker-compose.yml
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:3000
      - VITE_NODE_ENV=development
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
      - /app/node_modules
    command: npm run dev

  ms-gateway:
    environment:
      - NODE_ENV=development
    volumes:
      - ./gateway/src:/app/src
      - /app/node_modules

  database:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auditmesh_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password

  redis:
    ports:
      - "6379:6379"
